---
- name: Copying the index.html
  copy:
    src: templates/index.html.j2
    dest: /home/student/Projects/blog-app{{ item }}/templates/index.html
    owner: student
    mode: '0644'
  loop:
    - 1
    #- 2
    # Add the sequence below
  become: yes  
