---
- name: Check httpd status on web servers
  hosts: webservers
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Check if httpd is active
      service:
        name: httpd
        state: started
      register: httpd_status